name: Build and Deploy Code

# on:
#   push:
#     # branches: ["main","another_branch","feature_branch"]
#     - "main"
#     - "another-branch"
#   pull_request:
#     branches:
#       - "test_branch"

on : [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: set up python version 3.9
        uses: actions/setup-python@v2
        with:
          python-versopm: 3.9
        run: python --version
      